# Generated by Django 2.1.5 on 2019-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rberry', '0002_auto_20190126_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temphumidity',
            name='u_on',
        ),
        migrations.AlterField(
            model_name='temphumidity',
            name='c_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
