# Generated by Django 2.1.5 on 2019-01-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rberry', '0003_auto_20190126_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temphumidity',
            options={'ordering': ['-c_on']},
        ),
    ]
